

name: Verificação de Build e Testes

on:
  [push, pull_request]

jobs:
  Build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Configurar JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'zulu'
  
        - name: Build Maven
          run: |
            cd api
            mvn -B package --file pom.xml

  Testes:
    needs: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configurar JDK 21 para testes
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Testes Unitários
        run: |
          cd api
          mvn test

  Deploy:
      runs-on: ubuntu-latest
      needs: [Build, Testes] # Só faz deploy após build e testes passarem
      if: |
        github.event_name == 'push' ||
        (
          github.event_name == 'pull_request' &&
          (
            startsWith(github.base_ref, 'main') ||
            startsWith(github.base_ref, 'sprint-')
          )
        )
      steps:
        - uses: actions/checkout@v4
        
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: 21
            distribution: 'zulu'
        
        - name: Build JAR
          run: |
            cd api
            mvn clean package -DskipTests