

name: Verificação de Build e Testes

on:
  [push, pull_request]

permissions:
    contents: write
    pull-requests: write

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  Build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Configurar JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'zulu'
  
        - name: Build Maven
          run: |
            cd api
            mvn -B package --file pom.xml

  Testes:
    needs: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configurar JDK 21 para testes
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Testes
        run: |
          cd api
          mvn test

  Deploy:
      runs-on: ubuntu-latest
      needs: [Build, Testes] # Só faz deploy após build e testes passarem
      if: |
        (
          startsWith(github.base_ref, 'main') ||
          startsWith(github.base_ref, 'sprint-')
        ) && 
        (
          github.event_name == 'pull_request'
        )
      steps:
        - uses: actions/checkout@v4
        
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: 21
            distribution: 'zulu'
        
        - name: Build JAR
          run: |
            cd api
            mvn clean package -DskipTests

  Aprovar:
    runs-on: ubuntu-latest
    needs: [Build, Testes, Deploy]
    steps:
        -   name: Aprovar PR
            uses: juliangruber/approve-pull-request-action@v1
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                number: ${{env.PR_NUMBER}}

  Mergear:
    runs-on: ubuntu-latest
    needs: [Build, Testes, Deploy, Aprovar]
    steps:
        -   name: Mergear PR
            uses: juliangruber/merge-pull-request-action@v1
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                number: ${{env.PR_NUMBER}}
                method: merge